default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 500
  timeout: 5000

  host: <%= ENV['POSTGRES_HOST'] %>
development:
  <<: *default
  database: supa_ai_development

test:
  <<: *default
  database: supa_ai_test
