default: &default
  adapter: postgresql
  encoding: unicode
  username: supa
  password: supa_development
  pool: 100
  timeout: 5000

  host: <%= ENV['POSTGRES_HOST'] %>
development:
  <<: *default
  database: supa_ai_development

test:
  <<: *default
  database: supa_ai_test
