default: &default
  adapter: postgresql
  encoding: unicode
  username: supa_ai
  password: supa_ai_development
  pool: 100
  timeout: 5000
  
  host: <%= ENV['POSTGRES_HOST'] %>
development:
  <<: *default
  database: supa_ai
test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>
production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
